<#
.SYNOPSIS
Regenerates tests/fixtures/playground-cases.json from the PowerShell module.

.DESCRIPTION
The PowerShell exporter is the reference implementation. This script runs the
scenarios in tests/fixtures/playground-inputs.json through the synthetic site
and the Prometheus renderer and records the exact output or error. Pester
checks that the file is current, and the Node suite checks that the Metrics
Playground produces the same bytes.
#>
[CmdletBinding()]
param(
    [string]$OutputPath = (Join-Path (Join-Path $PSScriptRoot 'fixtures') 'playground-cases.json')
)

$ErrorActionPreference = 'Stop'
$repositoryRoot = Split-Path -Parent $PSScriptRoot
$modulePath = Join-Path (Join-Path (Join-Path $repositoryRoot 'src') 'CitrixExporter') 'CitrixExporter.psd1'
Import-Module $modulePath -Force

$inputs = Get-Content -LiteralPath (Join-Path (Join-Path $PSScriptRoot 'fixtures') 'playground-inputs.json') -Raw |
    ConvertFrom-Json

$cases = foreach ($case in $inputs.cases) {
    # ConvertFrom-Json turns ISO 8601 strings into DateTime values, so normalize
    # to an explicit UTC offset instead of re-parsing a culture-formatted string.
    $at = if ($case.at -is [datetime]) {
        [DateTimeOffset]::new($case.at.ToUniversalTime())
    }
    else {
        [DateTimeOffset]::Parse($case.at, [System.Globalization.CultureInfo]::InvariantCulture)
    }
    $atText = $at.UtcDateTime.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", [System.Globalization.CultureInfo]::InvariantCulture)
    $entry = [ordered]@{ name = $case.name; at = $atText; scenario = $case.scenario }
    try {
        $entry.text = InModuleScope CitrixExporter -Parameters @{ Scenario = $case.scenario; At = $at } {
            param($Scenario, $At)
            ConvertTo-CitrixPrometheusText -Snapshot (Get-SimulatedCitrixSnapshot -Scenario $Scenario -At $At)
        }
    }
    catch {
        $entry.error = $_.Exception.Message
    }
    $entry
}

$selfMetrics = InModuleScope CitrixExporter {
    Get-CitrixExporterSelfMetric -Success $true -DurationSeconds 0.042 -ErrorCount 0 -Mode simulation
}

$document = [ordered]@{
    description = 'Generated by tests/Update-PlaygroundFixtures.ps1 from the PowerShell module. Do not edit by hand.'
    version = (Import-PowerShellDataFile -Path $modulePath).ModuleVersion
    selfMetrics = $selfMetrics
    cases = @($cases)
}
$json = ($document | ConvertTo-Json -Depth 10) -replace "`r`n", "`n"
[System.IO.File]::WriteAllText(
    $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath),
    $json + "`n",
    [System.Text.UTF8Encoding]::new($false)
)
